Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gf.line3d   (cx, cy, cz, phirange, newfig = [fig,ax], alpha = 0.4, color = 'black');
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-4-f2b26d5c28ee>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mgf[0m[0;34m.[0m[0mline3d[0m   [0;34m([0m[0mcx[0m[0;34m,[0m [0mcy[0m[0;34m,[0m [0mcz[0m[0;34m,[0m [0mphirange[0m[0;34m,[0m [0mnewfig[0m [0;34m=[0m [0;34m[[0m[0mfig[0m[0;34m,[0m[0max[0m[0;34m][0m[0;34m,[0m [0malpha[0m [0;34m=[0m [0;36m0.4[0m[0;34m,[0m [0mcolor[0m [0;34m=[0m [0;34m'black'[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'cx' is not defined

